spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: test1234
    url: jdbc:mysql://docker-mysql/Transacton?createDatabaseIfNotExist=true&sessionVariables=sql_mode='NO_ENGINE_SUBSTITUTION'&jdbcCompliantTruncation=false
    username: root
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 20
      idle-timeout: 600000
      maximum-pool-size: 50 
      auto-commit: true
      pool-name: HikariCorePool
      max-lifetime: 1800000
      connection-timeout: 30000
      leak-detection-threshold: 10000
      connection-test-query: select * from information_schema.tables limit 1   
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        jdbc:
          time_zone: GMT+1

server:
  tomcat:
    accept-count: 5
    max-connections: 200
    max-threads: 100
    
