FROM openjdk
EXPOSE 8888
ADD target/spring-cloud-config-server-0.0.1-SNAPSHOT.jar spring-cloud-config-server-0.0.1-SNAPSHOT.jar
ENTRYPOINT [ "java","-jar","/spring-cloud-config-server-0.0.1-SNAPSHOT.jar" ]
