spring:
  rabbitmq:
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 2s
          max-attempts: 5
          max-interval: 5s
          multiplier: 1
  springdoc:
    version: '@springdoc.version@'
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${jwk.set.uri}
management:
  endpoints:
    web:
      exposure:
        include: "*"